global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'neoproyectto'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:8000']

  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']